[workspace]
resolver = "2"
members = ["core", "syntax"]

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "My rust text editor"
authors = ["Douglas Rocha <79188161+dougrocha@users.noreply.github.com>"]
