[package]
name = "text"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true

[dependencies]
ropey = "1.6.1"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.12"
